services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
        laravel_env: ${APP_ENV}
        node_platform: ${NODE_PLATFORM}
      context: ./
      dockerfile: Dockerfile
    image: laravel-mister-scrappy
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-compose/php.ini:/usr/local/etc/php/php.ini
      - ./docker-compose/php-fpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    networks:
      - mister-scrappy-network
    environment:
      PHP_IDE_CONFIG: serverName=localhost
networks:
  mister-scrappy-network:
    name: mister-scrappy-network-${APP_ENV}
    driver: bridge
